### ISSUE TITLE
clap Does not appear as a bundle in finder on macOS

### ISSUE THREAD

**Issue by baconpaul** [free-audio/clap-juce-extensions#17]
Right now it is missing so we just look like a folder etc...

**Comment by audiority** [comment]
the generated Info.plist has CFBundlePackageType set as APPL, while it needs to be BNDL. The plugins.plist.in (in clap src folder) seems to be correct. In order to make macOS see the folder as a package is to add a PkgInfo file, which is 8 bytes long, in the same folder of Info.plist. The content of this file is a concatenation of the values of CFBundlePackageType followed by CFBundleSignature. Ie: APPL???? or BNDL????
[PkgInfo.zip](https://github.com/free-audio/clap-juce-extensions/files/8984483/PkgInfo.zip)

**Comment by audiority** [comment]
<img width="489" alt="Schermata 2022-06-25 alle 12 28 31" src="https://user-images.githubusercontent.com/62889707/175769678-b6de47fa-4cbf-43d3-9c9b-2a82685555b7.png">

**Comment by baconpaul** [comment]
That is very very useful thank you

**Comment by baconpaul** [comment]
The above PR seems to work. Just testing ti with surge as well as the examples.

**Comment by baconpaul** [comment]
oh nope. it doesnt
damnit
do not merge this. 

It is close, but the use of ${CMAKE_SOURCE_DIRECTORY} is wrong

**Comment by baconpaul** [comment]
OK corrected
